CREATE TABLE ZhiFuBao(id integer primary key autoincrement,zhifubao text,passwd text,phone text,email text,ATM text,name text, taobao text);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "uc_number"(id integer primary key autoincrement,uc_number integer,uid integer,password char(20),phone char(13),mail char(20),nic text, username text);
CREATE TABLE uc_bbs(id integer primary key autoincrement,uc_number integer,username text,uid integer,password char(20), mail char(24));
CREATE TABLE IF NOT EXISTS "baidu"(id integer primary key autoincrement,username nchar(15),password char(15),phone char(12),mail char(20));
CREATE TABLE IF NOT EXISTS "pin"(id integer primary key autoincrement,username text,password integer, note varchar(10));
CREATE TABLE qq(id integer primary key autoincrement,qq integer,password varchar(20),mibao text);
CREATE TABLE IF NOT EXISTS "mail"(id integer primary key autoincrement,mail varchar(30),password varchar(20),phone integer, cl_pin varchar(20));
CREATE TABLE wx(id integer primary key autoincrement,weixin varchar(20),password varchar(20),phone integer,qq integer,mail varchar(30), user text);
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE program(id integer primary key autoincrement,username text,password varchar(20),addr text,phone varchar(20),mail varchar(30),class text,nic text, note text);
CREATE TABLE course(id integer primary key autoincrement,username text,password varchar(20),addr text,phone varchar(20),mail varchar(30),class text,nic text, note text);
CREATE TABLE sina(id integer primary key autoincrement,username text,password varchar(20),addr text,phone varchar(20),mail varchar(30),class text,nic text, note text);
CREATE TABLE IF NOT EXISTS "web"(id integer primary key autoincrement,username text,password varchar(20),addr text,phone varchar(20),mail varchar(30),class text,nic text, note text);
CREATE TABLE live(id integer primary key autoincrement,username text,password varchar(20),addr text,phone varchar(20),mail varchar(30),class text,nic text, note text);
CREATE TABLE video(id integer primary key autoincrement,username text,password varchar(20),addr text,phone varchar(20),mail varchar(30),class text,nic text, note text);
CREATE TABLE IF NOT EXISTS "life"(id integer primary key autoincrement,username text,password varchar(20),addr text,phone varchar(20),mail varchar(30),class text,nic text, note text);
CREATE TABLE IF NOT EXISTS "mycard"(id integer primary key autoincrement,number blob,user ntext,use bit, name text);
